spring:
  cloud:
    gateway:
      routes:
        - id : r1
          uri : http://loclahost:8081
          predicates:
          - Path : /customers/**
        - id : r2
          uri : http://localhost:8082
          predicates:
          - Path : /products/**
      discovery:
        enable : false
  application:
    name : gateway-service
